// Placeholder for shared headers / declarations that need to be visible
// to both the .cu and the auto-generated PYBIND11_MODULE in main.cpp.
//
// The actual pybind binding is auto-generated by torch's load_inline
// from the `functions=[...]` argument in load_inline.py.

#include <torch/extension.h>
#include <string>
#include <cstdint>

void forward_sub(torch::Tensor A_inv);

void delta_h(
    torch::Tensor k, torch::Tensor u, torch::Tensor w, torch::Tensor g,
    torch::Tensor doc_chunk_start, torch::Tensor doc_chunk_count,
    torch::Tensor chunk_token_base,
    torch::Tensor v_new_out,
    torch::Tensor h_per_chunk, torch::Tensor h_final,
    int64_t num_chunks, int64_t H, int64_t HV
);

void wmma_delta_h(
    torch::Tensor k, torch::Tensor u, torch::Tensor w, torch::Tensor g,
    torch::Tensor doc_chunk_start, torch::Tensor doc_chunk_count,
    torch::Tensor chunk_token_base,
    torch::Tensor v_new_out,
    torch::Tensor h_per_chunk, torch::Tensor h_final,
    int64_t num_chunks, int64_t H, int64_t HV
);

void chunk_o(
    torch::Tensor q, torch::Tensor v_new, torch::Tensor g,
    torch::Tensor A_qk, torch::Tensor h_per_chunk, torch::Tensor chunk_token_base,
    torch::Tensor o, double scale_d, int64_t H, int64_t HV
);

torch::Tensor kda_fwd(
    torch::Tensor q,
    torch::Tensor k,
    torch::Tensor v,
    torch::Tensor g_cum,
    torch::Tensor beta,
    c10::optional<torch::Tensor> cu_seqlens_opt,
    double scale_d,
    c10::optional<torch::Tensor> initial_state_opt,
    bool output_final_state,
    int64_t BT_arg
);

std::string kda_fwd_version();
